base:
  project_name: mlflow-testing
  target: quality

load_dataset:
  bucket: datasetbucket
  filename: WineQT.csv
  raw_data: /data/raw

make_dataset:
  test_split: 0.25
  seed: 41
  processed_data: /data/processed
  res_seed: 42

build_features:
  extended_data: /data/extended

mlflow_config:
  # artifacts_dir: artifacts
  trainingExpName: modeltraining
  tunningExpName: modeltunning
  bestModelExpName: bestModel 
  remote_server_uri: http://ec2-54-227-78-19.compute-1.amazonaws.com:5000     # server running on ec2
  mlflow_tracking_uri: sqlite:///mlflow.db
  cmd: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./artifacts --host localhost -p 5000
  reg_model_name: 'outperforming models'
  stage: production

train_model:
  n_estimators: 50
  criterion: gini
  max_depth: 50
  min_samples_leaf: 30 
  random_state: 42
  min_samples_split: 60
  model_dir: /models

hyperopt:
  max_eval: 5
  model_name: best_model